name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Create Deployment
        run: |
          aws deploy create-deployment \
            --application-name "your-application-name" \ # ✅ CodeDeploy 애플리케이션 이름 입력
            --deployment-group-name "your-deployment-group-name" \ # ✅ CodeDeploy 배포 그룹 이름 입력
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
